### PR TITLE
Implement Functional Options

### PR DESCRIPTION
**Pull request by italolelis**
Hello,

As proposed in here #31, the following implements functional options into the library. This is a breaking change and should probably increase the major version. A few things to consider:

### Why? 
I started to have name conflicts with the options that were common to both clients since both of them are in the root folder of the project. Here is an example of the issue:

```go

httpClient := heimdall.NewHTTPClient(
	heimdall.WithHTTPTimeout(10), 
	heimdall.WithRetryCount(4),
)

hystrixClient := heimdall.NewHystrixHTTPClient(
	heimdall.WithHTTPTimeout(10), // This name cannot be the same
	heimdall.WithRetryCount(4),// This name cannot be the same
	heimdall.WithHystrixTimeout(1100),
)

```

For this reason, I thought it would be more elegant to have the client implementations in their own package. I called them `httpclient` (to avoid conflict with the `http` package) and `hystrix`

Now the usage looks like:

```go
	httpClient := httpclient.NewClient(
		httpclient.WithHTTPTimeout(timeout),
		httpclient.WithRetryCount(2),
	)

	hystrixClient := hystrix.NewClient(
		hystrix.WithHTTPTimeout(timeout),
		hystrix.WithCommandName("MyCommand"),
		hystrix.WithHystrixTimeout(1100),
		hystrix.WithMaxConcurrentRequests(100),
		hystrix.WithErrorPercentThreshold(25),
		hystrix.WithSleepWindow(10),
		hystrix.WithRequestVolumeThreshold(10),
	)
```

## Returning concrete types

Now I started to return concrete types on the constructors of the clients and to make sure the compiler can identify if we are implementing the interface I added this line.

```go
var _ heimdall.Client = (*Client)(nil)
```

If you don't like the packaging strategy please let me know and we can try to find a solution.

Thanks!

### CODE REVIEW

**Comment by rShetty** [comment]
@italolelis There are merge conflicts, can you help resolve these plz.

**Comment by italolelis** [comment]
@rShetty done

**Comment by rShetty** [comment]
@italolelis Skimmed through the PR. Overall looks solid and Thank you for this. Have added few comments.

**Comment by italolelis** [comment]
@rShetty Thanks for reviewing, I can't see the comments that you left though. Do I need to fix something?

**Comment by rShetty** [comment]
@italolelis Have commented

**Comment by rShetty** [comment]
Thank you very much for the PR

**Pull request merged**
