### PR TITLE
Add jitter for constant backoff

### PR DESCRIPTION
**Pull request by pravj**
As you're answering questions, I've created this small PR for the jitter requirement.

Currently, it's adding a random time (<= MAX) to the given backoff time.
We can discuss if you want a different way for this.

### CODE REVIEW

**Comment by pravj** [comment]
cc @rShetty

**Comment by rShetty** [comment]
@pravj Do you also want to add this jitter functionality for exponential backoff ?

**Comment by rShetty** [comment]
Also we need to the update the documentation of this change, thanks

**Comment by timusg** [comment]
@rShetty @pravj  raised the [PR](https://github.com/gojektech/heimdall/pull/22) for the Jitter functionality in the exponential backoff.

**Comment by rShetty** [comment]
@pravj @timusg Merging this. Will be adding documentation separately

**Pull request merged**
